# Site settings
author: Tiara
title: Tiara Hlaing
header-img: img/home-bg.png
email: tiara.hlaing@gmail.com
copyright_name: Tiara
description: > # this means to ignore newlines until "baseurl:"
  Journeying into the Deep
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thetiaramisu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
